### ISSUE TITLE
v2.1.1 cannot be loaded

### ISSUE THREAD

**Issue by MineCrocodile** [M0dEx/FunQuiz#4]
> [15:44:44] [Server thread/ERROR]: Could not load 'plugins/FunQuiz_v2.1.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:168) ~[spigot-1.15.2.jar:git-Spigot-8faa8b4-3d61a85]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:143) [spigot-1.15.2.jar:git-Spigot-8faa8b4-3d61a85]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:353) [spigot-1.15.2.jar:git-Spigot-8faa8b4-3d61a85]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:210) [spigot-1.15.2.jar:git-Spigot-8faa8b4-3d61a85]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-8faa8b4-3d61a85]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.util.zip.ZipException: zip END header not found
	at java.util.zip.ZipFile$Source.zerror(ZipFile.java:1535) ~[?:?]
	at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1436) ~[?:?]
	at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1443) ~[?:?]
	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1274) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1237) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:247) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:177) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:346) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:317) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:283) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:156) ~[spigot-1.15.2.jar:git-Spigot-8faa8b4-3d61a85]
	... 5 more

**Comment by MineCrocodile** [comment]
I delete and re-upload the plugin and it works this time. Don't know why is that. But it works now, thank you!

**Comment by M0dEx** [comment]
It was probably corrupted with the first upload.
